# Generated by Django 5.2.14 on 2026-05-23 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('draw_date', models.DateField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('profile_picture', models.URLField(blank=True, max_length=500)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('google_access_token', models.TextField(blank=True)),
                ('google_refresh_token', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=40)),
                ('direction', models.CharField(choices=[('buy', 'Customer buys foreign currency with MMK'), ('sell', 'Customer sells foreign currency for MMK')], max_length=8)),
                ('foreign_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('mmk_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate_used', models.DecimalField(decimal_places=4, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.currency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.DecimalField(decimal_places=4, help_text='MMK amount needed to buy 1 unit of this currency.', max_digits=16)),
                ('sell_rate', models.DecimalField(decimal_places=4, help_text='MMK amount paid when selling 1 unit of this currency.', max_digits=16)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate', to='exchange.currency')),
            ],
            options={
                'ordering': ['currency__sort_order', 'currency__code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('buy', 'Buy foreign currency with MMK'), ('sell', 'Sell foreign currency for MMK')], max_length=8)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Buy tiers use MMK amount. Sell tiers use foreign currency amount.', max_digits=18)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty for no upper limit.', max_digits=18, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=16)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='exchange.exchangerate')),
            ],
            options={
                'ordering': ['direction', 'min_amount'],
                'constraints': [models.UniqueConstraint(fields=('exchange_rate', 'direction', 'min_amount', 'max_amount'), name='unique_exchange_rate_tier_range')],
            },
        ),
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('bundle_size', models.PositiveSmallIntegerField(choices=[(1, '1 ticket'), (2, '2 ticket bundle'), (5, '5 ticket bundle'), (10, '10 ticket bundle')])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='available', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='exchange.lotterydraw')),
            ],
            options={
                'ordering': ['draw', 'number', 'bundle_size'],
                'constraints': [models.UniqueConstraint(fields=('draw', 'number', 'bundle_size'), name='unique_lottery_ticket_bundle_per_draw')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255)),
                ('device_name', models.CharField(blank=True, help_text='e.g., iPhone 12, Samsung Galaxy', max_length=255)),
                ('device_type', models.CharField(blank=True, help_text='e.g., ios, android, web', max_length=50)),
                ('fcm_token', models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications')),
                ('is_active', models.BooleanField(default=True, help_text='Only one device can be active at a time')),
                ('access_token', models.TextField(blank=True, help_text='JWT access token for this device')),
                ('refresh_token', models.TextField(blank=True, help_text='JWT refresh token for this device')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_login'],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='unique_user_device')],
            },
        ),
    ]
