# Generated by Django 5.2.14 on 2026-05-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeratetier',
            options={'ordering': ['sort_order', 'direction', 'min_amount']},
        ),
        migrations.AddField(
            model_name='exchangeratetier',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
