# Generated by Django 5.2.14 on 2026-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_exchangecommunicationchannel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangecommunicationchannel',
            options={'ordering': ['is_primary', 'sort_order', 'name'], 'verbose_name': 'Exchange Communication Channel', 'verbose_name_plural': 'Exchange Communication Channels'},
        ),
        migrations.AddField(
            model_name='exchangecommunicationchannel',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary contact method (email, phone, website) vs additional channels'),
        ),
        migrations.AlterField(
            model_name='exchangecommunicationchannel',
            name='platform',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('website', 'Website'), ('facebook', 'Facebook'), ('messenger', 'Facebook Messenger'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('line', 'LINE'), ('wechat', 'WeChat'), ('other', 'Other')], default='other', help_text='Platform type', max_length=20),
        ),
    ]
